# Generated by Django 4.0.2 on 2022-03-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
