# Generated by Django 4.0.2 on 2022-05-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('BadgeID', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('CNI', models.CharField(max_length=30, unique=True)),
                ('Image', models.ImageField(default=None, upload_to=None)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('fonction', models.CharField(default=None, max_length=30)),
                ('BirthdayDay', models.DateField(default=None, max_length=30)),
                ('Zone', models.CharField(default=None, max_length=30)),
                ('Permission', models.CharField(default=None, max_length=30)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
