# Generated by Django 4.0.2 on 2022-03-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Fullname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
